### ISSUE TITLE
Running vagrant alters Berksfile.lock

### ISSUE THREAD

**Issue by cjerdonek** [berkshelf/vagrant-berkshelf#110]
Maybe I have a misunderstanding of how the Vagrant plugin is supposed to work, but running `vagrant provision`, for example, alters Berksfile.lock as a side effect.  I would think it should just use your existing Berksfile.lock as is.

Not only that, if I run `berks update` before running `vagrant provision`, the latter still changes Berksfile.lock.  In other words, `berks` and `vagrant` seem to use different rules when updating Berksfile.lock.

Is this the intended behavior?  What rules does `vagrant provision` use to update Berksfile.lock?  Is there a workflow or way to use `vagrant` and `berks update` so they don't both undo each other's changes to Berksfile.lock?  Thanks for any info!

**Comment by franklinwise** [comment]
This problem still exists.  Please don't modify my Berkfile.lock file. My current solution is to delete the lock file every time I run vagrant up.
