### ISSUE TITLE
vagrant plugin install berkshelf-vagrant fails on windows 7

### ISSUE THREAD

**Issue by springyboing** [berkshelf/vagrant-berkshelf#15]
On a fresh install of vagrant (1.1.5) running on WIndows 7 64bit, i get the following error.  Any ideas?  Is this a plugin issue or Vagrant issue?

---

$ vagrant plugin install berkshelf-vagrant
Installing the 'berkshelf-vagrant' plugin. This can take a few minutes...
C:/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:556:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

```
    C:/vagrant/vagrant/embedded/bin/ruby.exe extconf.rb
```

creating Makefile

make
generating generator-i386-mingw32.def
compiling generator.c
make: gcc: Command not found
make: **\* [generator.o] Error 127

Gem files will remain installed in C:/Users/tim/.vagrant.d/gems/gems/json-1.7.7 for inspection.
Results logged to C:/Users/tim/.vagrant.d/gems/gems/json-1.7.7/ext/json/ext/generator/gem_make.out
        from C:/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:534:in `block in build_extensions'
        from C:/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:509:in`each'
        from C:/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:509:in `build_extensions'
        from C:/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:180:in`install'
        from C:/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:297:in `block in install'
        from C:/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:270:in`each'
        from C:/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:270:in `each_with_index'
        from C:/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:270:in`install'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/plugin/action/install_gem.rb:38:in `block in call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/plugin/gem_helper.rb:42:in`block in with_environment'
        from C:/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/user_interaction.rb:40:in `use_ui'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/plugin/gem_helper.rb:41:in`with_environment'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/plugin/action/install_gem.rb:28:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/plugin/action/bundler_check.rb:20:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builder.rb:109:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in`block in run'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in`run'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/plugin/command/base.rb:17:in `action'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/plugin/command/install.rb:44:in`execute'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/plugin/command/root.rb:47:in `execute'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/cli.rb:46:in`execute'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/environment.rb:408:in `cli'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.5/bin/vagrant:75:in`<top (required)>'
        from C:/vagrant/vagrant/embedded/gems/bin/vagrant:23:in `load'
        from C:/vagrant/vagrant/embedded/gems/bin/vagrant:23:in`<main>'

**Comment by neilmillard** [comment]
I deleted my %HOMEPATH%/.vagrant.d folder to solve this after upgrading vagrant
