### ISSUE TITLE
dep-selector-libgecode errors when installing 2.0.1 on Ubuntu 14.04

### ISSUE THREAD

**Issue by mikedep333** [berkshelf/vagrant-berkshelf#191]
I am not sure whether dep-selector-libgecode or vagrant-berkshelf is to blame, but I am having trouble installing vagrant-berkshelf 2.0.1 on Ubuntu 14.04 64-bit.

mike@dropship-hv:~/ddh/duckpan-vagrant :) [29] $ vagrant plugin install vagrant-berkshelf --plugin-version '>= 2.0.1'
Installing the 'vagrant-berkshelf --version '>= 2.0.1'' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing dep-selector-libgecode (1.0.0), and Bundler cannot continue.
Make sure that `gem install dep-selector-libgecode -v '1.0.0'` succeeds before bundling.
mike@dropship-hv:~/ddh/duckpan-vagrant :( [30] $ sudo gem install dep-selector-libgecode -v '1.0.0'
Building native extensions.  This could take a while...
Successfully installed dep-selector-libgecode-1.0.0
1 gem installed
Installing ri documentation for dep-selector-libgecode-1.0.0...
unable to convert "\xED" from ASCII-8BIT to UTF-8 for lib/dep-selector-libgecode/vendored-gecode/include/gecode/int.hh, skipping
unable to convert "\xE4" from ASCII-8BIT to UTF-8 for lib/dep-selector-libgecode/vendored-gecode/include/gecode/int/sorted.hh, skipping
unable to convert "\xED" from ASCII-8BIT to UTF-8 for lib/dep-selector-libgecode/vendored-gecode/include/gecode/int/cumulative.hh, skipping
unable to convert "\xF3" from ASCII-8BIT to UTF-8 for lib/dep-selector-libgecode/vendored-gecode/include/gecode/int/gcc.hh, skipping
unable to convert "\xED" from ASCII-8BIT to UTF-8 for lib/dep-selector-libgecode/vendored-gecode/include/gecode/int/unary.hh, skipping
unable to convert "\xE9" from ASCII-8BIT to UTF-8 for lib/dep-selector-libgecode/vendored-gecode/include/gecode/int/distinct.hh, skipping
Installing RDoc documentation for dep-selector-libgecode-1.0.0...
unable to convert "\xED" from ASCII-8BIT to UTF-8 for lib/dep-selector-libgecode/vendored-gecode/include/gecode/int.hh, skipping
unable to convert "\xE4" from ASCII-8BIT to UTF-8 for lib/dep-selector-libgecode/vendored-gecode/include/gecode/int/sorted.hh, skipping
unable to convert "\xED" from ASCII-8BIT to UTF-8 for lib/dep-selector-libgecode/vendored-gecode/include/gecode/int/cumulative.hh, skipping
unable to convert "\xF3" from ASCII-8BIT to UTF-8 for lib/dep-selector-libgecode/vendored-gecode/include/gecode/int/gcc.hh, skipping
unable to convert "\xED" from ASCII-8BIT to UTF-8 for lib/dep-selector-libgecode/vendored-gecode/include/gecode/int/unary.hh, skipping
unable to convert "\xE9" from ASCII-8BIT to UTF-8 for lib/dep-selector-libgecode/vendored-gecode/include/gecode/int/distinct.hh, skipping
mike@dropship-hv:~/ddh/duckpan-vagrant :) [31] $ vagrant plugin install vagrant-berkshelf --plugin-version '>= 2.0.1'
Installing the 'vagrant-berkshelf --version '>= 2.0.1'' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing dep-selector-libgecode (1.0.0), and Bundler cannot continue.
Make sure that `gem install dep-selector-libgecode -v '1.0.0'` succeeds before bundling.
mike@dropship-hv:~/ddh/duckpan-vagrant :( [32] $ gem install dep-selector-libgecode -v '1.0.0'
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /var/lib/gems/1.9.1 directory.
mike@dropship-hv:~/ddh/duckpan-vagrant :( [33] $ sudo vagrant plugin install vagrant-berkshelf --plugin-version '>= 2.0.1'
Installing the 'vagrant-berkshelf --version '>= 2.0.1'' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing dep-selector-libgecode (1.0.0), and Bundler cannot continue.
Make sure that `gem install dep-selector-libgecode -v '1.0.0'` succeeds before bundling.

**Comment by xacaxulu** [comment]
+1

**Comment by dduft** [comment]
Great job Mike, thanks a lot!
