### ISSUE TITLE
Missing vagrant-vmware-workstation plugin

### ISSUE THREAD

**Issue by michalbachowski** [berkshelf/vagrant-berkshelf#197]
Hi,

after upgrade of Vagrant on OS X I tried to install berkshelf, but without success:

``` bash
$vagrant plugin install vagrant-berkshelf --plugin-version '>= 2.0.1'
Net::HTTPNotFound: No gems found matching "vagrant-vmware-workstation" "2.4.1" nil
```

I use VirtulBox provisioner on OS X 10.9.3:

``` bash
$vagrant -v
Vagrant 1.5.4
```

``` bash
$vagrant plugin list
vagrant-login (1.0.1, system)
vagrant-share (1.0.1, system)
vagrant-vbguest (0.10.0)
```

Is this problem related to berkshelf itself or Vagrant internals?

Best regards

Michał Bachowski

**Comment by F3TTT** [comment]
Ditto.  Was trying to install vagrant-hostupdater and ran into this problem.  Had to retry over a dozen times and then magically it worked.  Doubt it was a horked install.  The error message itself states that it may be a transient network condition.  Win 7.

**Comment by geerlingguy** [comment]
Ditto again. Never had an issue until today, but it took 6 tries before I was able to finally install `vagrant-hostsupdater`.

**Comment by tknerr** [comment]
Having the same thing every now and then. 

Since it uses bundler for installing the plugins under the hood, can we configure the bundler settings somehow? 

I have this in my `~/.bundle/config` but it seems not to be respected by vagrant:
```
BUNDLE_JOBS: 16
BUNDLE_RETRY: 3
```

In general  the `bundle install --retry <times>` option seems appropriate to me in order to fix this

**Comment by josesaldana** [comment]
Hello.  

Found in another post this: 
```
gem install --install-dir ~/.vagrant.d/gems vagrant-triggers -v '0.4.2'
```

After running that you could try to install the vagrant-hostupdater package again and see.

Regards,
Jose
