### ISSUE TITLE
getting error on attempted use, do I have bad ruby version? is this a vagrant error / berks error / ruby error?

### ISSUE THREAD

**Issue by paul42** [berkshelf/vagrant-berkshelf#216]
On a windows system:

``` text
ruby --version: ruby 2.0.0p451 (2014-02-24) [i386-mingw32]
```

I installed chef-dk (0.2.0) and the newest vagrant from the web site (1.6.3) when I do a 'berks cookbook myApp' and change the image (from the ubuntu one to config.vm.box = "chef/centos-6.5") I get the following error on vagrant up:

``` text
Bringing machine 'default' up with 'virtualbox' provider...
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir': No such file or directory - H: (Errno::ENOENT)
```

Doing a regular vagrant init / vagrant up with that box works. 

On my other machine at home, I am able to use vagrant and berkshelf without issues, got a full provision going.

**Comment by langionen** [comment]
What commands did you run to set your HOME HOMEDIR and HOMEPATH via commandline to %USERPROFILE%?

**Comment by paul42** [comment]
I can't remember now but I just googled 'windows command line set environment variables' as far as developing on windows and ruby, if you're having tooling issues can i recommend a release from @tknerr 's bill's kitchen? https://github.com/tknerr/bills-kitchen/releases it's the bee's knees and Toben is super helpful! it packs everything you need in a nice area and sets it up well. I can't recommend it enough.
