### ISSUE TITLE
Error occurred: no implicit conversion of Proc into String

### ISSUE THREAD

**Issue by oguzy** [berkshelf/vagrant-berkshelf#227]
I am trying to up a test this: https://github.com/stackforge/monasca-vagrant

Using Ubuntu 14.04, Vagrant 1.6.5 and Virtualbox 4.3.10

vagrant up gives the below error:

[@sethvargo edit], moved stacktrace to gist: https://gist.github.com/sethvargo/8892ef246da6f45785ae

**Comment by muelli** [comment]
I've also run into this issue.  The snippet a few comments up works.  I have to make the if condition a tautology, though.
