### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by heffergm** [berkshelf/vagrant-berkshelf#237]
I'm a little mystified by this. I'd been using vagrant-berkshelf 2.x for a while without issue. Having upgraded to 4.0.0, I'm in the following situation:
- the initial `vagrant up` proceeds without issue, however if I halt and then restart the box, or try to reprovision it, I get the following error:

```
Vendoring yum-epel (0.5.1) to /Users/grant/.berkshelf/vagrant-berkshelf/shelves/berkshelf20141117-36310-1or3u6-default/yum-epel

    stderr: /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1402:in `initialize': Permission denied @ rb_sysopen - /Users/grant/.berkshelf/vagrant-berkshelf/shelves/berkshelf20141117-36310-1or3u6-default/pelias/.git/objects/02/6d813fd34b114e7deae1eb2c98afed1c1e7f13 (Errno::EACCES)
    from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1402:in `open'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1402:in `block in copy_file'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1401:in `open'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1401:in `copy_file'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:483:in `copy_file'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:400:in `block in cp'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1579:in `block in fu_each_src_dest'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1595:in `fu_each_src_dest0'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1577:in `fu_each_src_dest'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:399:in `cp'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/file_syncer.rb:88:in `block in sync'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/file_syncer.rb:71:in `each'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/file_syncer.rb:71:in `sync'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:617:in `block in vendor'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:577:in `vendor'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:387:in `vendor'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:52:in `dispatch'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:27:in `execute!'
    from /opt/chefdk/embedded/apps/berkshelf/bin/berks:5:in `<top (required)>'
    from /opt/chefdk/bin/berks:38:in `load'
    from /opt/chefdk/bin/berks:38:in `<main>'
```

If I `rm -rf /Users/grant/.berkshelf/vagrant-berkshelf`, I can run successfully, but again, subsequent attempts will fail.

Any idea what's going on? No commands are being run with sudo or as different users, etc. The perms on the files that I get the access error for are 444, owner/group as I'd expect.

... and it would appear that a `chmod -R 755 ~/.berkshelf/vagrant-berkshelf/` resolves the problem.

**Comment by franklinwise** [comment]
This is not an edge case.  When can we see a new release of Berkshelf + ChefDK?

**Comment by sethvargo** [comment]
@franklinwise unfortunately we have no control over the release cycles of ChefDK. Berkshelf is already out and updated.

**Comment by franklinwise** [comment]
@sethvargo - understand, thanks

**Comment by gionn** [comment]
new Chef-DK 0.4.0 is out but this fix isn't included, isn't it?

**Comment by quietcat** [comment]
It seems to happen when there are git repos in cookbook subfolders. Building on @ericcitaire and @brk3  comments I changed '.git' to '**/.git' in `EXCLUDED_VCS_FILES_WHEN_VENDORING = ['.arch-ids', '{arch}', '.bzr', '.bzrignore', '.bzrtags', 'CVS', '.cvsignore', '_darcs', '.git', '.hg', '.hgignore', '.hgrags', 'RCS', 'SCCS', '.svn'].freeze` line in /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb

**Comment by josacar** [comment]
Same happens to me after upgrading to chefdk 0.4.0

**Comment by joaocunha** [comment]
The workaround for me was:

```
vagrant destroy --force
rm -rf ~/.berkshelf
#@quietcat's change in berksfile.rb
vagrant up
```

Worth mentioning my `vagrant up` build was failing due to network errors, so a VPN played a big role.

**Comment by acorncom** [comment]
joelhandwell's script referenced above works for me.

I'm using chefdk 0.4.0, Vagrant 1.7.2 and vagrant-berkshelf 4.0.3

**Comment by levmichael3** [comment]
@joaocunha  and @quietcat it worked for me as well, thanks!
Instead of deleteing the berkshelf shelf each time and run provision making the '**/.git' change made the trick.

ERROR was about the 'sendmail' community cookbook:


    stderr: /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1402:in `initialize': Permission denied @ rb_sysopen - /home/****/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150217-4295-1fixznz-default/sendmail/.git/objects/21/ffa1b33b817de42e4f2b20adf69c801594b217 (Errno::EACCES)

**Comment by chicobico** [comment]
Thx for the quick fix.
With '**/.git' it works.

**Comment by mikeyhill** [comment]
I'm still getting this error:

    stderr: /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1402:in `initialize': Permission denied @ rb_sysopen - /Users/me/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150529-46153-19rn0ai-default/loggly/.git/objects/00/184054f177e4a255995d68205efdf6c127762a

Berkshelf: 3.2.3
ChefDK: 0.4.0

The fix mentioned above doesn't work for me, the .git directory is excluded already (along with numerous others) in berksfile.rb

**Comment by mrjcleaver** [comment]
+1 for @quietcat 's https://github.com/berkshelf/vagrant-berkshelf/issues/237#issuecomment-72906999 workfing
