### ISSUE TITLE
vagrant up creates berkshelf with .svn directories included

### ISSUE THREAD

**Issue by brianrepko** [berkshelf/vagrant-berkshelf#251]
I have an svn working directory of all our in-house cookbooks as well as a Berksfile that does a cookbook for each directory it finds (with a metadata.rb file).  When I do a vagrant up, the resulting berkshelf is including the .svn directories for all the locally sourced cookbooks.  This creates a problem when I do a reload or halt / up as I start getting file permission problems on the .svn folder files.

I'm on Windows7 with ChefDK 0.3.5, berkshelf 3.2.1, vagrant 1.7.1 and vagrant-berkshelf 4.0.2.
I believe I have */.svn/* in the chefignore file but I don't think that applies to this.

**Comment by sethvargo** [comment]
This was fixed in https://github.com/berkshelf/berkshelf/commit/2ddc01c50c3df14dacbcd26114c4e5c923098ccc#diff-4b548ac8d4318ae6d66dcb631bdae051, which is v3.2.2.

**Comment by brianrepko** [comment]
aha - great! now to get that included in ChefDK
