### ISSUE TITLE
vagrant-berkshelf always enabled

### ISSUE THREAD

**Issue by allaire** [berkshelf/vagrant-berkshelf#253]
Hi,

I have vagrant-berkshelf installed as a plugin, and it always get enabled, even if I don't set it to true and even if there is no Berksfile.

 simple test case:

Just download the LAMP stack here: http://rove.io/?pattern=lamp (or any other combinaison) (it uses librarian-chef).

No matter what, I get:

```
default: /tmp/vagrant-chef/029912a6cbf35881060ab8c894427836/cookbooks => /Users/allaire/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150113-5857-1wc7nws-default
```

manually specifying `config.berkshelf.enabled = false` seems to fix it, BUT when I `vagrant reload`, and then try to run `vagrant provision` again, I get the following:

```
Shared folders that Chef requires are missing on the virtual machine.
This is usually due to configuration changing after already booting the
machine. The fix is to run a `vagrant reload` so that the proper shared
folders will be prepared and mounted on the VM.
```
**EDIT**
Looks like my second issue is more related to this: https://github.com/mitchellh/vagrant/pull/5121

**Comment by sethvargo** [comment]
Hi @allaire,

Can you please run the Vagrant command in debug mode and Gist the output? The output should say "why" the plugin is being enabled.

**Comment by allaire** [comment]
@sethvargo Here, `vagrant up --debug`:

https://gist.github.com/allaire/438c290979390c0645f2

**Comment by sethvargo** [comment]
@allaire ahhh. I think I see the problem. I think you might be hitting [this bug](https://github.com/berkshelf/vagrant-berkshelf/commit/2a16051a4d4be2e43a696b848a95f055b2c2db88) which is fixed on master, but is currently unreleased.

**Comment by allaire** [comment]
@sethvargo Ok cool, if you could ping back here when you cut a new release that would be awesome.

Have a great day!

**Comment by sethvargo** [comment]
@allaire can you build from master and try and see if it fixes your issue?

1. Clone the rep
2. Run `rake build`
3. Run `vagrant plugin install /path/to/repo/pkg/vagrant-berkshelf-4.0.2.gem`

**Comment by allaire** [comment]
@sethvargo That did it I think, thanks! Though I still get the `Shared folders that Chef requires are missing on the virtual machine.` on `vagrant reload`, but I think that's a vagrant error...

**Comment by sethvargo** [comment]
@allaire yea, that's a Vagrant error that I'm also going to fix soonish(tm)
