### ISSUE TITLE
Vagrant up can't find Berkshelf

### ISSUE THREAD

**Issue by daften** [berkshelf/vagrant-berkshelf#256]
I have ChefDK installed and it is in front of my path. vagrant is installed (through brew) and vagrant-berkshelf is installed. I use chruby to manage ruby versions and zsh as a shell.
However, when I issue vagrant up (also in a folder where it worked before), I get the following error:

```
The following berks command failed to execute:

    /opt/vagrant/bin/../embedded/bin/berks --version --format json

The stdout and stderr are shown below:

    stdout:
    stderr: /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'berkshelf' (>= 0) among 71 total gem(s) (Gem::LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /opt/vagrant/bin/../embedded/bin/berks:22:in `<main>'


It appears that you are not using the ChefDK. Please note that Vagrant Berkshelf
works best when used with the ChefDK, and other installation methods are not
officially supported.

Please download and install the latest version of the ChefDK from:

    https://downloads.getchef.com/chef-dk

and follow the installation instructions. Do not forget to add the ChefDK to
your PATH.
```

This doesn't happen with the 3.0.1 version of this plugin.

```text
echo $PATH: /opt/chefdk/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
Any additional debug info I can give, I'd be more than happy to help, but I'm stuck in figuring this out ATM.

**Comment by sethvargo** [comment]
I think this is an issue with Vagrant's embedded Ruby. It's not leaving the embedded Ruby enough to let us reach the Chef DK. What happens if you run `which berks` on your machine? What version of Vagrant are you using?

**Comment by daften** [comment]
which berks: /opt/chefdk/bin/berks, forgot to mention that.
vagrant is installed via brew (cask), so 1.7.1 atm

I tried running gem install with the embedded gem executable within vagrant, but I get a ton of other errors then, so I quickly uninstalled/deleted everything, rebooted, and reinstalled to start fresh. That makes me think it's not an issue with my machine config, but one of the elements. Could very well be vagrant, I performed an update of brew cask before the trouble started.

**Comment by daften** [comment]
Sorry, it's 1.7.2, updated on jan6 in the repo. I'll see if I can reproduce with 1.7.1 tonight, if not -> vagrant.

Thanks for the quick reply

**Comment by sethvargo** [comment]
@daften ugh that's not good. Vagrant may have remnants of your attempt to install Berkshelf previously. Can you completely uninstall vagrant and remove everything in `~/.vagrant.d` and try again?

**Comment by daften** [comment]
I just uninstalled vagrant through brew cask, and installed version 1.7.1 via the pkg with a download. It works.
Then I uninstalled vagrant (removed /opt/vagrant and /usr/bin/vagrant, removed ~/.vagrant.d), removed the .vagrant folder in the project to be safe, and installed vagrant 1.7.2. (same uninstall and install steps), and it works too.
Then installed vagrant through cask, and it works.

The only difference I see is i might have forgotten to delete the ~/.vagrant.d folder yesterday, I didn't think a small upgrade could cause problems with that.

Thanks for the help!

**Comment by NeMO84** [comment]
I had this issue as well. I was using ChefDK -> Berkshelf and Vagrant. 

Turned out that when I used `berks cookbook services` to create a new cookbook template it produces a Gemfile. And when I ran `bundle install` to install the dependencies for the cookbook workflow, it installed a version of Berkshelf outside of the ChefDK. Then running `vagrant up` caused the above error. 

I confirmed that the wrong version was being used by running `which berks` which produced <rvm_path> + "/bin/berks". I was expecting the "/usr/bin/berks" since I am using the Berkshelf from ChefDK. 

I resolved this by running `gem uninstall berkshelf` from within the gemset I was using. This removed the version that the Gemfile caused to install. I then issue the `vagrant up` command again and all worked as expected. 

Is it okay for me to assume that anytime I use berks from ChefDK, I should install dependencies using `chef exec bundle install` to avoid issues in the future?

**Comment by lsmolic** [comment]
+1 @NeMO84  Thanks so much, this was driving me nuts.

**Comment by bikbajwa** [comment]
I tried the solution you provided @NeMO84 but I still can't get it to work.

I am receiving the following error on vagrant up:
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
The following berks command failed to execute:

    c:\users\bajwab\.chefdk\gem\ruby\2.1.0\bin/berks.BAT --version --format json

The stdout and stderr are shown below:

    stdout:
    stderr: c:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:315
:in `to_specs': Could not find 'berkshelf' (>= 0) among 55 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=C:/Users/bajwab/.vagrant.d/gems;C:/HashiCorp/Vagrant/embedded/gems',
execute `gem env` for more information
        from c:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:32
4:in `to_spec'
        from c:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_
gem.rb:64:in `gem'
        from c:/Users/bajwab/.chefdk/gem/ruby/2.1.0/bin/berks:22:in `<main>'
```

**Comment by wallydrag** [comment]
@bikbajwa try running `gem uninstall chef chef-zero berkshelf knife-solo`
