### ISSUE TITLE
Make the path to the shelf configurable via config option

### ISSUE THREAD

**Issue by tknerr** [berkshelf/vagrant-berkshelf#257]
It would be nice if the path to the [shelf created here](https://github.com/berkshelf/vagrant-berkshelf/blob/master/lib/vagrant-berkshelf/action/load.rb#L36-44) could be overridden via a config option.

Rationale:

* some people prefer to have the resolved cookbook dependencies nearer to the project (e.g. in `.vagrant/berks-cookbooks/`) or the like
* you see the whole context with only the vagrant project open in your editor -- no need to open `$HOME/.berkshelf/<project>/vagrant/<generated>` in a separate editor window
* you could set this in your global Vagrantfile so it transparently applies to all projects

**Comment by sethvargo** [comment]
@tknerr you can set `ENV["BERKSHELF_PATH"]` to override that path if you'd like. However, the "shelves" are not something the end user should concern themselves with. They are an implementation detail and internal to Vagrant Berkshelf.

**Comment by tknerr** [comment]
Thanks @sethvargo, I will give it a try!l
Am 16.01.2015 16:49 schrieb "Seth Vargo" <notifications@github.com>:
