### ISSUE TITLE
rsync cookbooks not working

### ISSUE THREAD

**Issue by ramarnat** [berkshelf/vagrant-berkshelf#260]
Not sure if this is a Vagrant core issue or not. The rsync based copy of the cookbooks fails:

```
EBUG subprocess: Command not in installer, not touching env vars.
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: Warning: Permanently added '172.19.2.59' (RSA) to the list of known hosts.
DEBUG subprocess: stdout: building file list ...
DEBUG subprocess: stdout: done
DEBUG subprocess: stderr: rsync: mkdir "/tmp/vagrant-chef/5b59e7bf6935f70c97ce4ff6249d5974/cookbooks" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at /usr/src/ports/rsync/rsync-3.0.9-1/src/rsync-3.0.9/main.c(587) [Receiver=3.0.9]
DEBUG subprocess: stderr: rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /SourceCache/rsync/rsync-45/rsync/io.c(453) [sender=2.6.9]
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31998
```

Host is OSX, Vagrant Guest is AWS Windows with cygwin, openssh, rsync installed.

Looks like the target rsync path needs to be pre-created because rsync doesnt issue a `mkdir -p`?

**Comment by sethvargo** [comment]
Hi @ramarnat,

Please see https://github.com/berkshelf/vagrant-berkshelf/issues/215

**Comment by ramarnat** [comment]
@sethvargo before I open an issue in the Vagrant core, I want to check with you. I would have expected by using `provisioning_path` I could work around this issue by pre-creating the target directory, But I see that in mitchellh/vagrant/pull/5121 the counter has been changed to an md5 of the local path, so there's no way to force the pre-creation of the target directory?

I guess I could hack it by creating an md5 of the localpath and using that in the pre-create, but would need to know the shelf path in advance, and that is embedded in the shelving code?

**Comment by sethvargo** [comment]
@ramarnat it's not a core issue - we create and destroy the target path on each run.

**Comment by ramarnat** [comment]
I am not sure I understand.

When I set `provisioning_path = /tmp` the error is:

```
Error: Warning: Permanently added '172.19.2.59' (RSA) to the list of known hosts.
rsync: mkdir "/tmp/5b59e7bf6935f70c97ce4ff6249d5974/cookbooks" failed: No such file or directory (2)
```

Based on  mitchellh/vagrant#5121 it seems to me that `/tmp/5b59e7bf6935f70c97ce4ff6249d5974/cookbooks` is set by the vagrant core as the remote_path by the chef-solo provisioner rather than the berkshelf plugin. Or did you mean the vendoring target path?

S

**Comment by ramarnat** [comment]
I changed this to use a local berks vendored directory instead of this plug-in and it still failed. I will open an issue on the Vagrant core
