### ISSUE TITLE
Cookbooks are not shared with VM after reload, restart [4.0.2]

### ISSUE THREAD

**Issue by IvanChepurnyi** [berkshelf/vagrant-berkshelf#263]
When first time I run a vagrant up, the cookbooks are shared correctly, and any consecutive call to vagrant provision works like expected. However, if I halt my VM and do up again, any provision with chef fails, since the directory is not shared with VM. 

Important findings about this:
First time in console there is an info that directory is shared:
```
==> default: Mounting shared folders...
    default: /tmp/vagrant-cache => /Volumes/ssd/work/vagrant.d/cache/chef/centos-6.6
    default: /tmp/vagrant-chef/935a7167a832e4dd48a4755c2e19dcad/cookbooks => /Users/ivan/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150209-58460-1gr07n0-default
==> default: Chef 11.16.4 Omnibus package is already installed.
```

When I restart VM there is only one directory shared:
```
==> default: Mounting shared folders...
    default: /tmp/vagrant-cache => /Volumes/ssd/work/vagrant.d/cache/chef/centos-6.6
==> default: Chef 11.16.4 Omnibus package is already installed.
```

Also if I remove a file in `.vagrant/machines/default/virtualbox/berkshelf` everything gets shared again. I expect it is happing because of bugfix introduced in [4.0.0]
(https://github.com/berkshelf/vagrant-berkshelf/blob/41b16bba0fa708d8d628c2caef3b495228cad185/CHANGELOG.md#400)

**Comment by sethvargo** [comment]
This is a Vagrant core issue: https://github.com/mitchellh/vagrant/issues/5199
