### ISSUE TITLE
Vagrant only mounts share for new machines with Vagrant 1.7.2

### ISSUE THREAD

**Issue by slbmeh** [berkshelf/vagrant-berkshelf#265]
```
$ vagrant --version && vagrant plugin list
Vagrant 1.7.2
vagrant-berkshelf (4.0.2)
vagrant-share (1.1.3, system)
```

With `chef_solo` and `chef_zero` provisioners with the default shared folder type and nfs.  It's looking like this is a bug in vagrant because I see the warden calls to `VagrantPlugins::Berkshelf::Action::Share`.

I can't quite pinpoint what isn't happening.

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/issues/5199
