### ISSUE TITLE
Vagrant reload --provision → Cookbook not found

### ISSUE THREAD

**Issue by alappe** [berkshelf/vagrant-berkshelf#271]
Hey,

on a recent project I am having the problem that on reload, the cookbook cannot be found. I am using vagrant, vagrant-berkshelf, berks (from chefdk) – the provisioning works fine on initital `up`.

```rb
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure('2') do |config|
  config.berkshelf.enabled = true
  config.omnibus.chef_version = :latest
  config.vm.hostname = 'falcon.dev'
  config.vm.box = 'chef/centos-7.0'

  config.vm.provider 'virtualbox' do |v, override|
    v.memory = 4096
    v.cpus = 1
  end

  config.vm.network 'private_network', ip: '192.168.14.77'

  config.vm.provision 'shell', inline: 'iptables --flush', run: 'always'
  config.vm.provision 'chef_solo' do |chef|
    chef.add_recipe 'falcon'
  end

  config.vm.synced_folder '~/Sites/Falcon/Code', '/usr/local/falcon/', type: 'nfs'
end
```

The Berksfile is super basic:

```
source 'https://supermarket.getchef.com'

metadata
```

The `/tmp/vagrant-chef/solo.rb` lists `/tmp/vagrant-chef/44008a4b553d0caf1bca7e96958dc206/cookbooks` as cookbook path, which is indeed empty.

So far I cannot tell if this is an issue with vagrant-berkshelf, I'm kind of fishing in the dark… but it seems that the cookbooks are not uploaded on the reload…

**Comment by sethvargo** [comment]
This is a Vagrant core issue: https://github.com/mitchellh/vagrant/issues/5199

**Comment by alappe** [comment]
@sethvargo Thank you!
