### ISSUE TITLE
Can not install vagrant-berkshelf

### ISSUE THREAD

**Issue by HuiguoRose** [berkshelf/vagrant-berkshelf#275]
root@iTears:/home# gem install berkshelf
Successfully installed berkshelf-3.2.3
1 gem installed

root@iTears:/home# vagrant plugin install vagrant-berkshelf
Installing the 'vagrant-berkshelf' plugin. This can take a few minutes...
Installed the plugin 'vagrant-berkshelf (4.0.3)'!
Post install message from the 'vagrant-berkshelf' plugin:

The Vagrant Berkshelf plugin requires Berkshelf from the Chef Development Kit.
You can download the latest version of the Chef Development Kit from:

https://downloads.getchef.com/chef-dk

Installing Berkshelf via other methods is not officially supported.

root@iTears:/home# chef -v
Chef Development Kit Version: 0.4.0

**Comment by HuiguoRose** [comment]
root@iTears:/home/tears# vagrant -v
Vagrant 1.4.3

**Comment by sethvargo** [comment]
@HuiguoRose there are no errors there. The recommended way to install chef is via the ChefDK, do not `gem install berkshelf`.

**Comment by HuiguoRose** [comment]
use ```
chef gem install berkshelf ``` does not work

**Comment by sethvargo** [comment]
Vagrant Berkshelf is a Vagrant plugin. You need to install the ChefDK and then install the Vagrant plugin:

```
$ vagrant plugin install vagrant-berkshelf
```

Then follow the instructions in the README for using the plugin.

**Comment by HuiguoRose** [comment]
Thank you very much I will try tomorrow @sethvargo

**Comment by HuiguoRose** [comment]
```root@iTears:/home/tears/下载# dpkg -r chefdk
(正在读取数据库 ... 系统当前共安装有 243304 个文件和目录。)
正在卸载 chefdk (0.4.0-1) ...

root@iTears:/home/tears/下载# chef -v
bash: /usr/bin/chef: 没有那个文件或目录

root@iTears:/home/tears/下载# berks -v
bash: /usr/bin/berks: 没有那个文件或目录

root@iTears:/home/tears/下载# dpkg -i chefdk_0.4.0-1_amd64.deb
正在选中未选择的软件包 chefdk。
(正在读取数据库 ... 系统当前共安装有 200757 个文件和目录。)
正准备解包 chefdk_0.4.0-1_amd64.deb  ...
正在解包 chefdk (0.4.0-1) ...
正在设置 chefdk (0.4.0-1) ...
Thank you for installing Chef Development Kit!

root@iTears:/home/tears/下载# vagrant plugin install vagrant-berkshelf
Installing the 'vagrant-berkshelf' plugin. This can take a few minutes...
Installed the plugin 'vagrant-berkshelf (4.0.3)'!
Post install message from the 'vagrant-berkshelf' plugin:

The Vagrant Berkshelf plugin requires Berkshelf from the Chef Development Kit.
You can download the latest version of the Chef Development Kit from:

    https://downloads.getchef.com/chef-dk

Installing Berkshelf via other methods is not officially supported.

root@iTears:/home/tears/下载# chef -v
Chef Development Kit Version: 0.4.0

root@iTears:/home/tears/下载# berks -v
3.2.3
```

**Comment by sethvargo** [comment]
@HuiguoRose I don't understand your issue? It looks like everything installed correctly from that output. Are you getting confused by the post-install message?

**Comment by HuiguoRose** [comment]
I don’t quite understand  that output.  
But But when I execute command ```` vagrant up ````
The terminal will print an error
 ```` root@iTears:/workspace/Vagrant-PHP-Stack# vagrant up
Failed to load the "vagrant-berkshelf" plugin. View logs for more details. ```

**Comment by sethvargo** [comment]
Can you reproduce the issue with a simpler Vagrantfile? There are a lot of moving pieces in that repository.

Also, Ruby does not like when you have non-ASCII characters in your $PATH. You might be experiencing that issue since it looks like `下载` is part of your $PATH.
