### ISSUE TITLE
Updating Vagrant's Berkshelf... - performance

### ISSUE THREAD

**Issue by lioramilbaum** [berkshelf/vagrant-berkshelf#277]
this step is copying the whole folder contents (where Berksfile resides) to C:\Users\user\.berkshelf\vagrant-berkshelf\shelves\berkshelf20150412-5652-15ib835-base folder.

It takes hours in case the folder contents include huge files, like zip files. Why is it necessary to perform the copy?

Thanks,
Liora

**Comment by sethvargo** [comment]
@lioramilbaum we need to perform the copy so we can share the files with Vagrant. May I ask - why do you have zip files in your Chef cookbooks? The Chef Server has a limit on the size of a cookbook that may be uploaded.

**Comment by lioramilbaum** [comment]
The zip files are used for deploying several applications. They are placed in my project root folder because it is automatically mounted with the guest /vagrant folder.

**Comment by dkinzer** [comment]
@lioramilbaum I think this is a vagrant issue.  The folder containing the Vagrantfile is auto mounted by vagrant.  However, it is possible to disable that option if you don not require that behavior:

`config.vm.synced_folder ".", "/vagrant", disabled: true`

http://docs.vagrantup.com/v2/synced-folders/basic_usage.html

Sadly there is no way (at least not that I know of) to have more discrete control over what gets synced or not. vagrant-berkshelf, however, does expose some configuration options that give you way more control over what is synced at the root cookbook level via `vm.berkshelf.only` and `vm.berkshelf.execept` config options.
