### ISSUE TITLE
Bug with installation of berkshelf

### ISSUE THREAD

**Issue by DarkofWarfare** [berkshelf/vagrant-berkshelf#278]
Hello, 

I've got a problem with installation of Berkshelf. Can you see an error with a screenshot ?
![My Screen](http://i.imgur.com/eoNZEsY.png)

**Comment by sethvargo** [comment]
Hi @DarkofWarfare 

Thank you for opening an issue. This is not an issue with the Vagrant Berkshelf plugin, but rather an issue with your Vagrant installation. It seems like your Vagrant install is in a bad state (since vmware-fusion is a Mac-based product).
