### ISSUE TITLE
vagrant provision not working after upgrade to 4.0.3, cannot find cookbook

### ISSUE THREAD

**Issue by dkinzer** [berkshelf/vagrant-berkshelf#279]
So I'm not quite sure if this a a vagrant issue or a vagrant-berkshelf issue:  

```
berks version: 3.2.3
vagrant version: 1.7.2
vagrant-berkshelf (4.0.3)

```

My Vagrantfile config was working prior to updating, but now it is failing with an error that it cannot find the cookbook.  When I ssh into the machine I see that my cookbook is not listed under the cookbooks folder but the files do appear in a folder called `/vagrant`

If I symlink the  `/vangrant` folder to  `../cookbooks/mycookbook`  then the provision works.

My Berksilfe is very simple:

```
source "https://api.berkshelf.com"

metadata
```

**Comment by dkinzer** [comment]
Note the above workaround fails if shared folders are rsynced instead of mounted (like to provision an aws instance)

**Comment by sethvargo** [comment]
Looks like https://github.com/mitchellh/vagrant/issues/5199

**Comment by dkinzer** [comment]
@sethvargo I think it may be related.  But this is one step further.  The folders are syncing just not quite right.  This might actually be an issue with berks.  Because when I look at .berksfile folder in the local machine, I see that cookbook is not added to `~/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150501-23411-1t44z7u-ezproxy-dev`

**Comment by dkinzer** [comment]
@sethvargo though maybe it is an effect of applying 

```
existing = synced_folders(@machine, cached: false)
```

Which I did to get past that issue.

**Comment by dkinzer** [comment]
I'm closing this because I think it might have been a local issue.  Everything works fine after I deleted the old  ~/.berkshelf folder and removed the `berkshelf` file inside `.vagrant` folder at the project level.
