### ISSUE TITLE
Setting enabled to false doesn't disabled vagrant-berkshelf

### ISSUE THREAD

**Issue by patcon** [berkshelf/vagrant-berkshelf#289]
When setting this in Vagrantfile, I'm still getting cookbook installation and folder syncing:

```rb
config.berkshelf.enabled = true
```

Is this expected behaviour?

**Comment by sethvargo** [comment]
Please share your complete Vagrantfile.

**Comment by patcon** [comment]
Hm. I've just been working away, rebooting lots, and just now realized that it's been disabled. Closing out, but I'll reopen if it comes back.
