### ISSUE TITLE
Support for Berkshelf 5.x

### ISSUE THREAD

**Issue by sauliust** [berkshelf/vagrant-berkshelf#305]
Vagrant Berkshelf requires ~> 4.0, but the current version is 5.1.0.

**Comment by omobono** [comment]
Broken on os x with latest xcode, vagrant, berkshelf and vagrant-berkshelf:

<img width="1082" alt="screen shot 2016-09-26 at 21 55 51" src="https://cloud.githubusercontent.com/assets/4202816/18851465/0fc086cc-8434-11e6-92ac-4d419c92bfae.png">

**Comment by jameyg** [comment]
Broken on os x with latest xcode, vagrant, berkshelf and vagrant-berkshelf:

<img width="1082" alt="screen shot 2016-09-26 at 21 55 51" src="https://cloud.githubusercontent.com/assets/752314/18851495/3ec35af8-8434-11e6-9141-d51eb13c5a64.png">

**Comment by microweb10** [comment]
I am having the same issue on Ubuntu 14.04 after upgrading chefDK and vagrant to the latest. Previously same Vagrant file was working fine

$ chef -v
Chef Development Kit Version: 0.18.26
chef-client version: 12.14.89
delivery version: master (d86679335580be3de22996ef294b20d525889d8d)
berks version: 5.1.0
kitchen version: 1.13.0

$ vagrant -v
Vagrant 1.8.5

$ vagrant plugin update
Updating installed plugins...
All plugins are up to date.

$ vagrant up default
Bringing machine 'default' up with 'virtualbox' provider...
The Berkshelf version at "/usr/bin/berks" is invalid.
Vagrant Berkshelf requires ~> 4.0, but the current version is 5.1.0.

Please download and install the latest version of the ChefDK from:

    https://downloads.chef.io/chef-dk

and follow the installation instructions. Do not forget to add the ChefDK to
your PATH.

Any workaround?

**Comment by astlock** [comment]
The same problem! Any idea?

**Comment by microweb10** [comment]
This worked for me.

Edit this file
~/.vagrant.d/gems/gems/vagrant-berkshelf-5.0.0/lib/vagrant-berkshelf/action/check.rb

where you see:
BERKS_REQUIREMENT = "~> 4.0"
change it to:
BERKS_REQUIREMENT = "~> 5.0"

**Comment by davidcpell** [comment]
same problem here. 

OSX 10.11.6
ChefDK 0.18.26 
vagrant-bekshelf 5.0

@microweb10's solution seems to have worked for me

**Comment by CharlesTBetz** [comment]
seems to have fixed for me as well

Ubuntu 16.04
ChefDK 0.18.26 
vagrant-berkshelf 5.0

**Comment by drwahl** [comment]
Not sure why this ticket is closed. Should there not be a patch to fix this in the upstream code? Manually editing the check.rb file is a workaround, not a fix.

**Comment by ericgoedtel** [comment]
That isn't really a good solution, in my opinion. Isn't .vagrant.d in .gitignore? This is not exactly a portable change. It works fine on an individual change but it doesn't really work for a Vagrant implementation that is shared amongst a distributed team. Anyone have any feedback on a permanent fix?

**Comment by microweb10** [comment]
After the approval of this PR, you should be able to upgrade vagrant-berkshelf plugin and the issue should be gone ;)

https://github.com/berkshelf/vagrant-berkshelf/pull/306

**Comment by Dreeg** [comment]
The solution of @microweb10 worked for me 👍

**Comment by ericgoedtel** [comment]
For some reason, the formal fix that implements the workaround isn't passing CI. May want to use with caution.

**Comment by Dreeg** [comment]
@ericgoedtel where can we get evidence?

**Comment by nickma** [comment]
Same issue here on all fresh OSX and Vagrant install. 
Workaround from @microweb10 works.

**Comment by thommay** [comment]
Fixed by #307, we'll do a release soon.

**Comment by daften** [comment]
Can a release be made please. I have to make every new dev perform this fix now :s

**Comment by thommay** [comment]
This was released in 5.1.1 in December.
