### ISSUE TITLE
[Question] Plugin usefulness in a post-Test Kitchen world

### ISSUE THREAD

**Issue by chris-fa** [berkshelf/vagrant-berkshelf#308]
I read in the `README.md` that after Test Kitchen, the maintainers feel like this plugin usefulness is questionable. I'm guessing from that line that this plugin was meant to provision a VM so you can **test your recipe**.

In my case, (being new to Chef, just 2 days into it) I'm using Chef to provision both our local and production machines. Chef Manage handles the production servers. But local machines are not a node. So basically I'm using `chef_solo` vagrant provisioner and `vagrant-berkshelf` (to resolve Berkshelf dependencies) to quickly provision local machines that have near-as-same configuration as our production servers.

My question is, what I am doing, does it make this plugin's usefulness less questionable, or is there a "better" way to solve berks dependencies when provisioning a vagrant VM for local development?

**Comment by sesslerp** [comment]
I have the exact same question. Some clearing up on that issue would be nice...

**Comment by tas50** [comment]
I'd highly recommend you use test kitchen for your local development vs. vagrant boxes. It's just a wrapper for vagrant that lets you define your systems in a simpler way and ties in nicely with Chef. In that case there is little value for this plugin.
