### ISSUE TITLE
FATAL: ArgumentError: You must specify at least one cookbook repo path

### ISSUE THREAD

**Issue by mconigliaro** [berkshelf/vagrant-berkshelf#78]
This error pops up at the end of the initial provision after you `rm -rf ~/.berkshelf` (which I have to do quite frequently due to https://github.com/RiotGames/berkshelf/issues/781 ):

`FATAL: ArgumentError: You must specify at least one cookbook repo path`

A simple workaround for now is to run `vagrant reload`.

**Comment by Karamcse** [comment]
Fatal error: you must specify '--save', '--no-save' or '--vanilla'
